### ISSUE TITLE
Clarify which M92 change for newer firmware version

### ISSUE THREAD

**Issue by wtip** [ysoldak/MPMD-CuraSettings#2]
`
Be advised newer Mini Deltas (firmware v43) have improved stepper drivers with better resolution, so you'll need make changes to start gcode and use 114.28 instead of 57.14 in M92 command.
`
I think the E value would also need to be changed based on the information I see here https://www.mpminidelta.com/howto/extruder_calibration

Maybe it would just make sense to add a commented line in cfg file with the alternate settings for the newer firmware.

```
; Use this M92 line instead if you're using firmware 43 & up
; M92 X114.28 Y114.28 Z114.28 E97.00
```

Your XYZ values match with what's on the wiki but your E value is different. How did you come up with that value?

**Comment by ysoldak** [comment]
Thanks, forgot about extruder, added that now.  
The thing is I'm not running the stock FW on this delta anymore, and don't remember all the settings.

> your E value is different

Yes, I've [calibrated my MPMD extruder](https://www.matterhackers.com/articles/how-to-calibrate-your-extruder) and that value is true for my bot, your _millimetrage_ may differ.

**Comment by ysoldak** [comment]
Closing

**Comment by wtip** [comment]
Which FW are you running on your printer these days? Anything you can recommend?

**Comment by ysoldak** [comment]
I run Klipper, but that requires new electronics. At least until we have port on STM32F0 chip. Look here https://github.com/ysoldak/MPMD/blob/master/klipper/README.md

With stock electronics you have an option to run Marlin port https://github.com/mcheah/Marlin4MPMD
